version: "3.7"
services:
    app:
        build: .
        ports:
            - "8080:8080"
        depends_on:
            - postgres

    postgres:
        image: postgres:14-alpine
        volumes:
            - ./postgres:/var/lib/postgres
        environment:
            - POSTGRES_DB=ranking_personagens
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        ports:
            - "5432:5432"
